<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selectPicture</name>
   <tag></tag>
   <elementGuidId>956cb918-ef4c-47b0-9045-10b3b3c41965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadPicture']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadPicture</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>200d190b-6afd-4469-8203-7e73e19ecfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadPicture</value>
      <webElementGuid>9f9ccb67-5173-4479-beea-c0e3cc58b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e446a478-af1b-448e-b0d6-1d0456cd5323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>f0796049-e078-4527-b60b-1cd1108dec88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>0d22ddb2-7f8d-4ab9-afe8-8d430b58ad1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadPicture&quot;)</value>
      <webElementGuid>d160720e-f671-41dc-a19b-14a2f3040b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadPicture']</value>
      <webElementGuid>1e415e89-83b9-414d-a362-1a73805b979c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userForm']/div[8]/div[2]/div/input</value>
      <webElementGuid>422f6006-73dc-4278-88bd-318e3bb2c084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/input</value>
      <webElementGuid>69c88a72-ba21-4612-b317-ecc09a069394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uploadPicture' and @type = 'file']</value>
      <webElementGuid>7bd4f6e8-12d6-4827-8206-ac167586516f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
