<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>input_</description>
   <name>input_pass</name>
   <tag></tag>
   <elementGuidId>69582a8d-8451-48b4-94cc-4f42f681a9da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
