<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Book Store API_basic-addon2</name>
   <tag></tag>
   <elementGuidId>277983bb-a4fa-43fc-a2da-e2710321dff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic-addon2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='basic-addon2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6ea4169-4d7a-4c2b-ace8-2c554719af0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>b8b326bf-833c-42c7-85a2-dd2d9faa7d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic-addon2</value>
      <webElementGuid>e86a26cf-a810-4df1-855e-9d443977f11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-addon2&quot;)</value>
      <webElementGuid>38aec026-9c46-44a6-976b-ef51544b10a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='basic-addon2']</value>
      <webElementGuid>f2cc5118-ac7e-4cd0-a1ee-ba2d779db369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchBox-wrapper']/div/div/div/span</value>
      <webElementGuid>aa0296c4-084e-4d1a-8288-3c48e7fedd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::span[1]</value>
      <webElementGuid>87c2a019-81f1-49dd-ae45-6f56f99176a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::span[2]</value>
      <webElementGuid>1123d0e5-4259-4985-b176-c4dacad58e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name :'])[1]/preceding::span[2]</value>
      <webElementGuid>2bb2730c-af8c-471c-9450-f4f5eef64f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jsantosmtz'])[1]/preceding::span[2]</value>
      <webElementGuid>ee4995e9-306b-45c1-9362-329c62302925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/span</value>
      <webElementGuid>3239c503-d973-4616-8d5c-bf06f942a406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'basic-addon2']</value>
      <webElementGuid>10ce845a-3b89-4cd7-bfe7-9258db2c2619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
